on:
  push:

jobs:
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: get flutter
        uses: subosito/flutter-action@v2

      - name: run format
        run: flutter format --line-length 120 --set-exit-if-changed ./lib

      - name: analyze code
        run: flutter analyze